# Generated by Django 3.1.7 on 2021-05-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=120, unique=True)),
                ('supplier_email', models.EmailField(max_length=64)),
                ('supplier_phone', models.BigIntegerField()),
                ('supplier_address', models.CharField(max_length=120)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
