# Generated by Django 3.1.7 on 2021-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_phone',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
